/*
 *
 * Home constants
 *
 */

export const DEFAULT_ACTION = 'app/Home/DEFAULT_ACTION';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';
export const SET_PARAMS_ARTICLES = 'SET_PARAMS_ARTICLES';
export const GET_ARTICLES_BY_TAGS = 'GET_ARTICLES_BY_TAGS';
export const SET_FAVORITER = 'SET_FAVORITER';